CREATE TABLE perfis(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE usuarios_perfis(
    usuario_id BIGINT NOT NULL,
    perfil_id BIGINT NOT NULL,

    PRIMARY KEY(usuario_id, perfil_id),
    CONSTRAINT USUARIOS_PERFIS_FK_USUARIO FOREIGN KEY(usuario_id) REFERENCES usuarios(id),
    CONSTRAINT USUARIOS_PERFIS_FK_PERFIL FOREIGN KEY(perfil_id) REFERENCES perfis(id)

);

INSERT INTO perfis(nome) VALUES('ADMIN');
INSERT INTO perfis(nome) VALUES('DIRETOR');
INSERT INTO perfis(nome) VALUES('SECRETARIO');
INSERT INTO perfis(nome) VALUES('COORDENADOR');
INSERT INTO perfis(nome) VALUES('ESTUDANTE');
INSERT INTO perfis(nome) VALUES('PROFESSOR');
INSERT INTO perfis(nome) VALUES('ORIENTADOR');
INSERT INTO perfis(nome) VALUES('RECURSOS_HUMANOS');
INSERT INTO perfis(nome) VALUES('RESPONSAVEL');
