-- Alter atualizado_em from DATE to TIMESTAMPTZ and add criado_em, criado_por

ALTER TABLE alertas ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE alertas ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE alertas ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE alunos ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE alunos ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE alunos ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE anotacoes ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE anotacoes ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE anotacoes ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE arquivos ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE arquivos ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE arquivos ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE aulas ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE aulas ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE aulas ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE avaliacoes ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE avaliacoes ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE avaliacoes ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE chamadas ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE chamadas ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE chamadas ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE comunicados ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE comunicados ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE comunicados ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE comunicados_usuario ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMPTZ;
ALTER TABLE comunicados_usuario ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE comunicados_usuario ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE conteudos ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE conteudos ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE conteudos ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE coordenadores ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE coordenadores ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE coordenadores ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE dados_autenticacao ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE dados_autenticacao ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE dados_autenticacao ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE dados_pessoais ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE dados_pessoais ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE dados_pessoais ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE diretores ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE diretores ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE diretores ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE disciplinas ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE disciplinas ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE disciplinas ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE disponibilidade_professor ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE disponibilidade_professor ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE disponibilidade_professor ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE fichas_medicas ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE fichas_medicas ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE fichas_medicas ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE grupos_disciplinas ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE grupos_disciplinas ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE grupos_disciplinas ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE horarios ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE horarios ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE horarios ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE laudos_medicos ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE laudos_medicos ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE laudos_medicos ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE notas ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE notas ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE notas ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE orientadores ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE orientadores ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE orientadores ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE perfis ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE perfis ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE perfis ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE planejamentos_anuais ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE planejamentos_anuais ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE planejamentos_anuais ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE professores ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE professores ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE professores ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE recursos_humanos ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE recursos_humanos ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE recursos_humanos ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE responsaveis ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE responsaveis ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE responsaveis ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE secretarios ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE secretarios ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE secretarios ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE series ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE series ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE series ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE tarefas ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE tarefas ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE tarefas ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE telefones ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE telefones ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE telefones ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE turmas ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE turmas ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE turmas ADD COLUMN IF NOT EXISTS criado_por BIGINT;

ALTER TABLE unidades ALTER COLUMN atualizado_em TYPE TIMESTAMPTZ USING atualizado_em::TIMESTAMPTZ;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE unidades ADD COLUMN IF NOT EXISTS criado_por BIGINT;
