ALTER TABLE comunicados ALTER COLUMN conteudo TYPE TEXT;
ALTER TABLE comunicados_AUD ALTER COLUMN conteudo TYPE TEXT;

ALTER TABLE alertas ALTER COLUMN conteudo TYPE TEXT;
ALTER TABLE alertas_AUD ALTER COLUMN conteudo TYPE TEXT;
